SKOPT: INFO     Execution directory is /home/figaro/Dropbox/Projects/SKgen/skopt/src/skopt/test_Si
SKOPT: INFO     Logging starts at 2014-11-27 08:54:53.748793
SKOPT: INFO     Will do PSO for 2 generations or until max relative error is below 5.0 %
SKOPT: INFO     
SKOPT: INFO     Iteration (0, 0)
SKOPT: INFO     ============================================================
SKOPT: INFO     	DeltaE_Si_3p   :	0.00591245
SKOPT: INFO     	DeltaE_Si_3d   :	0.192754
SKOPT: INFO     	PotCompRad_Si_s:	3.42269
SKOPT: INFO     	PotCompRad_Si_p:	6.46763
SKOPT: INFO     	PotCompRad_Si_d:	6.45093
Traceback (most recent call last):
  File "./skopt.test--Si.py", line 142, in <module>
    main()
  File "./skopt.test--Si.py", line 137, in main
    swarm, stats = optimise()
  File "/home/figaro/Dropbox/Projects/SKgen/skopt/src/skopt/optimise.py", line 190, in __call__
    self.optimise(*self.optimargs[1],**self.optimargs[3])
  File "/home/figaro/Dropbox/Projects/SKgen/skopt/src/skopt/pso.py", line 292, in __call__
    return self.optimise(*args, **kwargs)
  File "/home/figaro/Dropbox/Projects/SKgen/skopt/src/skopt/pso.py", line 258, in optimise
    part.fitness.values, part.worstErr = self.toolbox.evaluate(part.renormalized, iteration)
  File "/home/figaro/Dropbox/Projects/SKgen/skopt/src/skopt/optimise.py", line 172, in evalfitness
    fitness = self.evaluate(parvalues, iteration)
  File "/home/figaro/Dropbox/Projects/SKgen/skopt/src/skopt/evaluate.py", line 318, in __call__
    return self.evaluate(parameters,iteration)
  File "/home/figaro/Dropbox/Projects/SKgen/skopt/src/skopt/evaluate.py", line 302, in evaluate
    ss.execute()
  File "/home/figaro/Dropbox/Projects/SKgen/skopt/src/skopt/system.py", line 104, in execute
    task()
  File "/home/figaro/Dropbox/Projects/SKgen/skopt/src/skopt/runtasksDFTB.py", line 102, in __call__
    return self.execute()
  File "/home/figaro/Dropbox/Projects/SKgen/skopt/src/skopt/runtasksDFTB.py", line 92, in execute
    process.wait()
  File "/usr/local/lib/python2.7/subprocess.py", line 1291, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/local/lib/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
